# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6c5fd4d9f0d1965aba824e808480ece818559dbc37bac770166bca5ddbd59fdec715e23b9f5543b69b28d2feb7f091ae29bf65ac3857727647014560431d2fa

test:
  secret_key_base: ed47cf859ee244b22a177b31a065c30433ab3485ce36cf1688ad8b1886e4513fb79fee7ebd21f5d2c616a75f862b6a5aa7441ff63e49008ae825950936c508c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
